name: Deploy Document
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Compile document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Remove everything except the build result
        run: find . ! -name 'main.pdf' -type f -exec rm -f {} +
        shell: bash
      - name: Initialize a new Git repository
        run: git init
        shell: bash
      - name: Deploy this repository
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: .
